#!/bin/bash
# Удалить пользователя test_user если он не существует
answer_u="y"
while [ $answer_u = "y" ]
do
echo -n "Введите (например test_user) имя ненужного пользователя: "
read user

read -p "Не ошибся?" answer
case $answer in
y) read -p "Введи правильно: " user;;
n) echo "Вот и молодец.";;
esac

if grep $user /etc/passwd
then
userdel -r $user
echo "С пользователем $user произошел несчастный случай.RIP."
else
echo "Пользователя $user итак нет."
fi

read -p "Ещё кого-нибудь грохнем? (y/n): " answer_u
echo ""
case $answer_u in
y) echo "Меньше народу - больше кислороду.";;
n) echo "Рука бойцов колоть устала..";;
esac
done